std_msgs/Header header
# Ellipsoid Method
float32 j_ellipsoid
geometry_msgs/Point x_ellipsoid
float32 t_ellipsoid
# PSO Algorithm
float32 j_pso
geometry_msgs/Point x_pso
float32 t_pso
# ALC-PSO Algorithm
float32 j_alc_pso
geometry_msgs/Point x_alc_pso
float32 t_alc_pso
# Nesterov Algorithm
float32 j_nesterov
geometry_msgs/Point x_nesterov
float32 t_nesterov
# Nelder-Mead Algorithm
float32 j_nelder_mead
geometry_msgs/Point x_nelder_mead
float32 t_nelder_mead